spring.application.name=scrapvendors


spring.datasource.url=jdbc:mysql://localhost:3306/scrapvendors
spring.datasource.username=root
spring.datasource.password=Pavi2211@


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.Type=TRACE